<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexndar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Manage skos collections'))?>

<p><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'index')) . '#addSkosCollection/1/'?>"><?php echo $this->translate('Create new skos collection')?> &raquo;</a></p>
<p><a href="<?php echo $this->url(array('action' => 'show-icons'))?>"><?php echo $this->translate('Manage icons')?> &raquo;</a></p>
<?php if ( ! count($this->skosCollections)):?>
<div class="note">
	<p><?php echo $this->translate('No skos collections.')?></p>
</div>
<?php else:?>
<table id="skos-collections-list">
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->translate('Scheme')?></th>
			<th><?php echo $this->translate('Collection')?></th>
			<th><?php echo $this->translate('Icon')?></th>
			<th><?php echo $this->translate('Delete')?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->skosCollections as $i => $skosCollection):?>
		<tr class="<?php echo $i % 2 ? 'even' : 'uneven'?>">
			<th scope="row"><?php echo $i+1?></th>
			<td>
				<?php if (isset($skosCollection['dcterms_title'])) :?>
					<?php echo $skosCollection['dcterms_title'][0]?>
				<?php else :?>
					<?php echo $skosCollection['uri']?>
				<?php endif?>
			</td>
			<td>
				<?php echo (isset($this->collectionsMap[$skosCollection['collection']]) ? $this->collectionsMap[$skosCollection['collection']] : '')?>
			</td>
			<td>
				<a id="<?php echo $skosCollection['uuid']?>" class="assign-icon" href="#" title="<?php echo $this->translate('Change Icon')?>">
					<?php if ( ! empty($skosCollection['iconPath'])):?>
						<img src="<?php echo $skosCollection['iconPath']?>" />
					<?php else:?>
						<span><?php echo $this->translate('no icon')?></span>
					<?php endif?>
				</a>
			</td>
			<td>
				<?php if (isset($this->skosCollectionsWithDeleteJobs[$skosCollection['uuid']])):?>
					<a href="<?php echo $this->url(array('controller' => 'jobs', 'action' => 'view', 'job' => $this->skosCollectionsWithDeleteJobs[$skosCollection['uuid']]))?>" title="<?php echo $this->translate('Go to the delete job details')?>"><?php echo $this->translate('A delete job exists')?></a>
				<?php else:?>
					<a class="delete" href="<?php echo $this->url(array('action' => 'delete', 'uuid' => $skosCollection['uuid']))?>" title="<?php echo $this->translate('Delete')?>"><?php echo $this->translate('Delete skos collection')?></a>
				<?php endif?>
			</td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
<?php endif?>

<?php 
$confirmationMessage = $this->translate('Are you sure you want to delete the skos collection?');
$js = <<<JS
window.addEvent('load', function() {
	$$('.delete').each(function (el) {
		el.addEvent('click', function (e) {
			e.preventDefault();
			if (confirm('{$confirmationMessage}')) {
				window.location.href = new Element(e.target).get('href');
			}
		});
	});
});
JS;
$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>

<div id="assign-icons-box" class="assign-icons-box do-not-show">
	<input type="hidden" class="schemeUuid" />
	<?php foreach ($this->uploadedIcons as $icon) :?>
		<img class="<?php echo $icon['iconFile']?>" src="<?php echo $icon['httpPath']?>" title="<?php echo $icon['iconFile']?>" />
	<?php endforeach?>
</div>

<?php
	$baseUrl = $this->url(array(), 'default', true);
	if ($baseUrl) $baseUrl = rtrim($baseUrl, '/').'/';
	$this->headScript(Zend_View_Helper_HeadScript::FILE, $baseUrl . 'assets/scripts/editor/conceptSchemesIcons.js');
?>